name: Enforce gitflow

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  branch-policy:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      contents: read
      pull-requests: read

    env:
      HEAD_REF: ${{ github.head_ref }}
      BASE_REF: ${{ github.base_ref }}

    steps:
      - name: Show refs
        run: |
          echo "HEAD_REF=${HEAD_REF}"
          echo "BASE_REF=${BASE_REF}"

      - name: Enforce branch flow
        uses: ncalteen/branch-enforcement@v2
        with:
          policy: |
            release/*:develop
            develop:feature/*
          head_ref: ${{ env.HEAD_REF }}
          base_ref: ${{ env.BASE_REF }}